###############################################################################################
# Referecne: https://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html
###############################################################################################
doctrine_migrations:
    migrations_paths:
        'App\Migrations': 'src/Migrations'

    storage:
        # Default (SQL table) metadata storage configuration
        table_storage:
            table_name: 'doctrine_migration_versions'
            version_column_name: 'version'
            version_column_length: 1024
            executed_at_column_name: 'executed_at'

    # Possible values: "BY_YEAR", "BY_YEAR_AND_MONTH", false
    organize_migrations: false

    # Path to your custom migrations template
    custom_template: ~

    # Run all migrations in a transaction.
    all_or_nothing: false

    # Adds an extra check in the generated migrations to ensure that is executed on the same database type.
    check_database_platform: true
    