framework:
    assets:
      json_manifest_path: '%kernel.project_dir%/public/assets/default/build/manifest.json'

webpack_encore:
    output_path: '%kernel.project_dir%/public/assets/default/build'
    builds:
        default: '%kernel.project_dir%/public/assets/default/build'
        developement: '%kernel.project_dir%/public/assets/developement/build'
