imports:
    - { resource: services/twig_extensions.yaml }
    - { resource: services/phpbrew.yaml }
    - { resource: services/commands.yaml }

parameters:
    siteTitle: 'VS My Projects 2'
    mailer_user: 'admin@myprojects.lh'
    lang: 'en'
    locale: 'en_US'
    php_versions_dir: '/opt/phpbrew/php'
    virtual_hosts_dir: '/etc/httpd/conf.d'

services:        
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    #twig.extension.date:
    #    class: Twig_Extensions_Extension_Date
    #    tags:
    #        - { name: twig.extension }
    
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
        autowire: true
        
    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        autowire: false
  
    ###################################
    # GREAT DEBUGGING
    ###################################
    my_blue_screen:
        class: 'Tracy\BlueScreen'
        properties:
            info:
                - 'environment: %kernel.environment%'

    vasek_purchart.tracy_blue_screen.tracy.blue_screen: '@my_blue_screen'
    
    ##################################
    # Form Types with Arguments
    ##################################
    App\Form\Type\HostOptions\ProjectHostLampOptionType:
        arguments: ['@vs_app.php_brew']
        tags: [form.type]
          
    #############################################################################  
